import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';

import LinkAccounts from '../components/LinkAccounts';

const App = () => {
  const [loggedIn, setLoggedIn] = useState(false);
  const [showLoginForm, setShowLoginForm] = useState(false);
  const [showRegistrationForm, setShowRegistrationForm] = useState(false);

  if (loggedIn) {
    return <LinkAccounts />;
  } else {
    return (
      <div>
        <div style={{ margin: '20px' }}>
          <button
            onClick={() => {
              setShowRegistrationForm(false);
              setShowLoginForm(true);
            }}
          >
            Login
          </button>
          &nbsp;&nbsp;&nbsp;
          <button
            onClick={() => {
              setShowLoginForm(false);
              setShowRegistrationForm(true);
            }}
          >
            Register
          </button>
        </div>
        <div>
          {showLoginForm && (
            <div style={{ textAlign: 'center' }}>
              <button onClick={() => setLoggedIn(true)}>Set logged in</button>
            </div>
          )}
          {showRegistrationForm && (
            <>
              <div>Hello this is my registration form</div>
            </>
          )}
        </div>
      </div>
    );
  }
};

export default function Home() {
  return (
    <>
      <Head>
        <title>CNA: joint-summary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <App />
      </main>
    </>
  );
}
