import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

const createLinkToken = async () => {
  const response = await fetch('/api/create_link_token', { method: 'POST' });

  if (!response.ok) console.log('error creating link token:', response.statusText);

  const data = await response.json();

  console.log('response, create link token:', data);
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App: joint-summary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <a onClick={createLinkToken}>Create Link Token</a>
        </div>
      </main>
    </>
  );
}
